sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy
  - pypy3

matrix:
  include:
    - python: 2.7
      env: CODESTYLE=true
    - python: 3.5
      env: CODESTYLE=true

install:
  - |
    if [[ $CODESTYLE ]]; then
      pip install pycodestyle
    else
      pip install pytest
      pip install .
    fi

script:
 - |
    if [[ $CODESTYLE ]]; then
      pycodestyle
    else
      py.test
    fi

notifications:
  on_success: change
