sudo: false
language: python
python: 3.8
env:
  - TOXENV=py36
  - TOXENV=py37
  - TOXENV=py38
  - TOXENV=py39
  - TOXENV=pypy3
  - TOXENV=codestyle

install: pip install tox

script: tox

notifications:
  on_success: change
