sudo: false
language: python
python: 3.5
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=codestyle

install: pip install tox

script: tox

notifications:
  on_success: change
